#!/usr/bin/python
__version__ = "0.1"
__author__ = "von Affenfels GmbH"

import sys, argparse, logging, logging.handlers, asyncore
from socketIO_client import SocketIO, BaseNamespace

logger = logging.getLogger()

class SoccerBowl(argparse.ArgumentParser):
    def __init__(self, *args, **kwargs):
        super(SoccerBowl, self).__init__(*args, **kwargs)

        self.add_argument("-d", "--debug", action = "store_true", help = "Enables debug output")
        self.add_argument("--syslog", action = "store_true", help = "Enables logging to syslog")
        
        self.__args = {}

    def on_test(self, *args):
        print("ON TEST", args)

    def _initSocketIo(self):
        self.__socketIo = SocketIO('iot.saij.de', 16666, BaseNamespace)
        self.__socketIo.on('test', self.on_test)
        self.__socketIo.emit('test2')

    def process(self):
        self.__args = vars(self.parse_args())

        if self.__args["syslog"]:
            syslog = logging.handlers.SysLogHandler(address = '/dev/log', facility = logging.handlers.SysLogHandler.LOG_DAEMON);
            syslog.setFormatter(logging.Formatter("soccerbowl: [%(levelname)s] %(message)s"))
            logger.addHandler(syslog)
        else:
            stdout = logging.StreamHandler()
            stdout.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
            logger.addHandler(stdout)

        if self.__args["debug"]:
            logger.setLevel(logging.DEBUG)
        else:
            logger.setLevel(logging.INFO)

        logging.getLogger('requests').setLevel(logging.WARNING)

        logger.info("Started SoccerBowl v%s" % __version__)

        self._initSocketIo()

        try:
            # Start loop
            # asyncore.loop()
            self.__socketIo.wait()
        except KeyboardInterrupt:
            print "Exiting\n"
            sys.exit(0)

        return True

# Main function
if __name__ == "__main__":
    parser = SoccerBowl()
    if (not parser.process()):
        parser.print_help()